
---
name: Go
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - .github/dependabot.yml
  workflow_dispatch:
concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: stable
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  release:
    needs: build
    # Only run release job on tags
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: stable
      - name: Build release - Linux amd64